# Generated by Django 5.2.17 on 2026-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregistratedmodels',
            name='Donate_Organ',
            field=models.CharField(max_length=100),
        ),
    ]
