# Generated by Django 5.2.17 on 2026-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_organapplicationmodels_block1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organapplicationmodels',
            name='Donate_Organ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
